export const cityNames = [
    "New York", "Los Angeles", "Chicago", "Houston", "Miami", "Toronto", "London", "Paris", "Sydney", "Tokyo",
    "Beijing", "Mumbai", "Cairo", "Rio de Janeiro", "Bangkok", "Istanbul", "Rome", "Berlin", "Moscow", "Dubai",
    "Lisbon", "Nairobi", "Cape Town", "Seoul", "Mexico City", "Madrid", "Amsterdam", "Stockholm", "Dublin", "Vienna",
    "Athens", "New Delhi", "Singapore", "Hanoi", "Prague", "Oslo", "Montreal", "Buenos Aires", "Sao Paulo", "Toronto",
    "Vancouver", "Seattle", "Dallas", "Atlanta", "Dublin", "Sydney", "Auckland", "Wellington", "Brussels", "Geneva",
    "Bangkok", "Manila", "Kuala Lumpur", "Jakarta", "Lima", "Bogota", "Caracas", "Lima", "Santiago", "Copenhagen",
    "Warsaw", "Budapest", "Zurich", "Helsinki", "Munich", "Hamburg", "Shanghai", "Hong Kong", "Seoul", "Mumbai",
    "Kolkata", "Bangalore", "Chennai", "Cape Town", "Nairobi", "Casablanca", "Copenhagen", "Vienna", "Prague",
    "Bucharest", "Budapest", "Lisbon", "Athens", "Istanbul", "Warsaw", "Kiev", "Moscow", "St. Petersburg", "Dubai",
    "Riyadh", "Doha", "Kuwait City", "Abu Dhabi", "Tel Aviv", "Jerusalem", "Amman", "Baghdad", "Tehran", "Karachi",
    "Mumbai", "Delhi", "Kathmandu", "Colombo", "Dhaka", "Yangon", "Hanoi", "Ho Chi Minh City", "Manila", "Phnom Penh",
    "Jakarta", "Sydney", "Melbourne", "Brisbane", "Perth", "Auckland", "Wellington", "Suva", "Nuku'alofa",
    "Apia", "Honiara", "Port Moresby", "Port Vila", "Nouméa", "Papeete", "Bora Bora", "Rarotonga", "Tahiti", "Hobart",
    "Darwin", "Adelaide", "Cairns", "Christchurch", "Wellington", "Rotorua", "Queenstown", "Auckland", "Dunedin",
    "Invercargill", "Hamilton", "Napier", "Palmerston North", "Tauranga", "Whangarei", "Nelson", "New Plymouth",
    "Gisborne", "Dunedin", "Queenstown", "Christchurch", "Cairns", "Gold Coast", "Brisbane", "Sydney", "Melbourne",
    "Adelaide", "Perth", "Auckland", "Wellington", "Nouméa", "Honiara", "Port Moresby", "Suva", "Apia",
    "Nuku'alofa", "Papeete", "Bora Bora", "Rarotonga", "Tahiti", "Hobart", "Darwin", "Canberra", "Sydney", "Melbourne",
    "Brisbane", "Gold Coast", "Adelaide", "Perth", "Auckland", "Wellington", "Suva", "Apia", "Honiara", "Port Moresby",
    "Port Vila", "Nouméa", "Papeete", "Bora Bora", "Rarotonga", "Tahiti", "Hobart", "Darwin", "Adelaide", "Cairns",
    "Canberra", "Newcastle", "Wollongong", "Geelong", "Ballarat", "Bendigo", "Launceston", "Albury", "Toowoomba",
    "Mackay", "Townsville", "Rockhampton", "Bundaberg", "Gladstone", "Hervey Bay", "Coffs Harbour", "Tamworth",
    "Port Macquarie", "Dubbo", "Orange", "Bathurst", "Wagga Wagga", "Wollongong", "Cairns", "Townsville", "Rockhampton",
    "Bundaberg", "Gladstone", "Mackay", "Hervey Bay", "Coffs Harbour", "Tamworth", "Port Macquarie", "Dubbo",
    "Orange", "Bathurst", "Wagga Wagga", "Albury", "Warrnambool", "Geelong", "Ballarat", "Bendigo", "Shepparton", "Mildura",
    "Dubbo", "Orange", "Bathurst", "Tamworth", "Coffs Harbour", "Lismore", "Wagga Wagga", "Albury", "Warrnambool", "Hervey Bay",
    "Mackay", "Rockhampton", "Bundaberg", "Gladstone", "Cairns", "Townsville", "Newcastle", "Wollongong", "Launceston",
    "Albury", "Warrnambool", "Dubbo", "Orange", "Bathurst", "Tamworth", "Coffs Harbour", "Lismore", "Wagga Wagga", "Hervey Bay",
    "Mackay", "Rockhampton", "Bundaberg", "Gladstone", "Cairns", "Townsville", "Newcastle", "Wollongong", "Launceston",
    "Warrnambool", "Dubbo", "Orange", "Bathurst", "Tamworth", "Coffs Harbour", "Lismore", "Wagga Wagga", "Albury", "Hervey Bay",
    "Mackay", "Rockhampton", "Bundaberg", "Gladstone", "Cairns", "Townsville", "Newcastle", "Wollongong", "Launceston",
    "Albury", "Warrnambool", "Dubbo", "Orange", "Bathurst", "Tamworth", "Coffs Harbour", "Lismore", "Wagga Wagga", "Hervey Bay",
    "Mackay", "Rockhampton", "Bundaberg", "Gladstone", "Cairns", "Townsville", "Newcastle", "Wollongong", "Launceston",
    "Ballarat", "Bendigo", "Shepparton", "Mildura", "Sunbury",
]  